name: Release

on:
  push:
    branches: [ master ]

jobs:
  release:
    name: Release new version
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        uses: actions/checkout@v2
      - name: Prepare repository
        run: git fetch --unshallow --tags
      - name: Run release script
        uses: ./.github/actions/auto-release-with-file-version-bump
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          GITHUB_WORKSPACE: GITHUB_WORKSPACE
          GITHUB_REPOSITORY: GITHUB_REPOSITORY
