name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build_latex"
  build_and_run_tests:
    name: Build all files
    runs-on: ubuntu-latest
    container:
      image: xucheng/texlive-small:latest
    defaults:
      run:
        shell: sh
    steps:
      - name: Set up repo
        uses: actions/checkout@v2
      - name: Install missing packages
        # uses: docker://xucheng/texlive-small:latest
        # with:
        #   args: tlmgr install silence appendixnumberbeamer
        run: |
          tlmgr install silence appendixnumberbeamer fira fontaxes mwe 
      - name: Build minimal examples
        run: |
          latexmk -pdf -file-line-error -interaction=nonstopmode demo.tex
        # uses: docker://xucheng/texlive-small:latest
        # with:
        #   args: latexmk -pdf -file-line-error -interaction=nonstopmode demo.tex
      - name: Run minimal script
        # run: |
        #   find . -type f -name '*.pdf' -exec convert -density 500 {}[0] {}.png \;
        uses: docker://alpine:edge
        with:
          args: sh ./local_commands.sh

