on:
  push:
    branches: [ master ]

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build docs
        run: |
          mkdir Documentation
          echo "Hello World" > Documentation/hello.txt
          echo "::error::Error message" 1>&2
      - name: Upload docs to wiki
        uses: SwiftDocOrg/github-wiki-publish-action@master
        with:
          path: "Documentation"
        env:
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

